[package]
name = "media-tweak"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next = "8.0.0"
iced = { version = "0.14.0", features = ["image", "tokio"] }
tokio = { version = "1.44.2", features = ["fs", "io-util", "process"] }
