[package]
name = "media-tweak"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next = "8.0.0"
iced = { version = "0.14.0", features = ["image-without-codecs", "smol"] }
rfd = "0.17.2"
smol = "2.0.2"
